// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

// Injectors from wire.go:

// 初始化应用
func InitGreeter() *Greeter {
	user := NewUser()
	greeter := NewGreeter(user)
	return greeter
}
